# Shared settings for Linux + macOS

# Font styles
italic_font                          auto
bold_font                            auto
bold_italic_font                     auto

# UX behavior
detect_urls                          yes
copy_on_select                       yes
confirm_os_window_close              0
shell_integration                    enabled

# Window layout + navigation
enabled_layouts                      grid
map ctrl+shift+right                 next_window
map ctrl+shift+left                  previous_window

# Window appearance
background_opacity                   0.95
window_padding_width                 10
window_margin_width                  0
window_border_width                  0
draw_minimal_borders                 no
hide_window_decorations              no

# Startup geometry
initial_window_width                 800
initial_window_height                600

# History + update checks
scrollback_lines                     -1
repaint_delay                        10
input_delay                          3
update_check_interval                0
